project_name: notion-auto-archive
before:
  hooks:
    - go mod download
builds:
  - id: "default"
    env:
      - CGO_ENABLED=0
    binary: "{{ .ProjectName }}"
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
archives:
  - builds:
      - "default"
    wrap_in_directory: true
dockers:
  - ids:
      - default
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-amd64"
    use_buildx: true
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/mrflynn/notion-auto-archive"
      - "--platform=linux/amd64"
  - ids:
      - default
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-arm64v8"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use_buildx: true
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/mrflynn/notion-auto-archive"
      - "--platform=linux/arm64/v8"
  - ids:
      - default
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-armv7"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-armv7"
    use_buildx: true
    dockerfile: Dockerfile
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/mrflynn/notion-auto-archive"
      - "--platform=linux/arm/v7"
docker_manifests:
  - name_template: "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-armv7"
  - name_template: "ghcr.io/mrflynn/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-arm64v8"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-armv7"
checksum:
  name_template: SHASUMS.txt
snapshot:
  name_template: "{{ .ShortCommit }}-rc"
changelog:
  sort: asc
  filters:
    exclude:
      - "^conf:"
      - "^test:"
      - "^docs:"
